### ISSUE TITLE
Cycle Unified

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs#425]
Discussion I had with @TylorS:

> What if instead of Cycle Diversity, we would only have Cycle xstream? And then for different stream libraries, the user applies xs.fromObservable/toObservable on the edges sources/sinks?
> In fact, we can even automatically apply, inside run(), xs.fromObservable(sink) if we detect that sink is not an xstream Stream.
> So it wouldnt even require stream library users to manually convert.
> Except we couldn't do that for sources, because the source may be a DOMSource.
> The motivation behind this is that it would make customElementify easier (which currently only supports xstream)
> And also make DOMSource typings simpler, and many other things, like onionify.

Reasons to do this (from most important to least):
- To make it easier for libraries like cycle-restart, cycle collection, onionify, customElementify, etc
- To reduce overhead with maintaining the Cycle.js codebase, allowing authors to move faster
- To make use of Observable spec that many stream libraries started supporting (after we had made Cycle Diversity)

Guarantees:
1. The stream library used in `main` matches the stream library used for `run` 
2. All drivers receive sinks as `xs` streams (must adapt locally if desired)
3. (Complex or simple) sources should be converted with `adapt` in driver code (because sources are given to `main`, and `adapt` matches the stream library used in `main`, see guarantee number 1)

This would involve:
- [x] Study its viability regarding migration for RxJS and most.js use cases
  - We are aiming for zero breaking changes
- [x] Opening a new branch to start these experiments cross-package
- [x] Make `@cycle/run`
- [x] Delete `@cycle/base`
- [x] Delete `@cycle/xstream-run`
- [x] Make `fantasy-observable` spec
- [x] Publish `@cycle/run` as RC
- [x] Update `@cycle/run` to TS 2.1
- [x] `@cycle/foo-run` to have `xstream2foo` function that converts from xs.Stream to the equivalent in foo, and `@cycle/foo-run` attaches this function to the global object before running `@cycle/run`
  - Sources need to be converted
    - Complex sources are converted in drivers when materialized to streams
    - Simple sources (streams) are converted in `run` (??)
  - Sinks don't, because they should all follow fantasy-observable spec and `@cycle/run` will 
expect every sink to be FO-compliant
  - [x] rxjs-run
  - [x] most-run
- [x] Delete the adapter libraries
- [x] Rewrite DOM Driver to use this global adapter in all types of sources
  - [x] sources should use `adapt()` from `@cycle/run`
  - [x] Rewrite tests in TypeScript
  - [x] use xstream in tests as well, also write them in TypeScript
  - [x] Make all tests pass
  - [x] Update snabbdom to 0.6.1
  - [x] Optional: Refactor EventDelegator
  - [x] Optional: Refactor IsolateModule
  - [x] Optional: Refactor scope vs fullScope
  - [x] Optional: Copy-paste matches-selector into our DOM Driver
  - [x] Optional: Check [should issues](https://github.com/cyclejs/cyclejs/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22scope%3A%20dom%22%20%20%20label%3A%22priority%203%20(should)%22%20) and [must issues](https://github.com/cyclejs/cyclejs/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22scope%3A%20dom%22%20%20%20label%3A%22priority%204%20(must)%22)
- [x] Rewrite HTTP Driver to use this global adapter in all types of sources
  - [x] Use new `run` and `adapt`
  - [x] Rewrite tests in TypeScript
  - [x] Make sure that res$ is adapted as well as res$$
- [x] Rewrite History Driver to depend directly on xstream and use this global adapter
  - [x] Use new `run` and `adapt`
  - [x] Fix back/forward tests
  - [x] Write JSDocs/README https://github.com/cyclejs/cyclejs/pull/465
- [x] Update HTTP to use latest superagent
- [x] Rewrite JSONP driver too
- [x] Make sure all other packages use TS 2.1
- [x] Make `@cycle/run` a hard dependency for all drivers that use `@cycle/run/lib/adapt`
- [x] Update all dependencies and devDependencies to latest versions
  - [x] Fix xstream https://github.com/staltz/xstream/issues/168
  - [x] Update testem, make sure DOM and HTTP and history tests pass
  - [x] Update saucie and reconfigure testem for it
  - [x] Reconfigure testem for Cycle history
  - [x] Turn off CI tests for Cycle history because of issue #514
  - [x] Fix Cycle DOM cross-browser issues
  - [x] Fix Cycle History cross-browser issues
  - [x] Update other dependencies in each package
- [x] **Release all as RC** 🇫🇰 🇫🇰 🇫🇰 🇫🇰 🇫🇰 on the **correct** dist-tags
- [x] Fix tests (see PR https://github.com/cyclejs/cyclejs/pull/516)
- [x] Rewrite matrix multiplication
- [x] Update examples
  - [x] Fix snabbdom https://github.com/snabbdom/snabbdom/issues/167
  - [x] Update isomorphic example after the above is solved **and released**
  - [x] Update other examples
  - [x] Update nested-folders to use onionify
- [x] Write release notes
  - [x] Communicate dependency on TS 2.1
  - [x] DOM driver no more transposition
  - [x] HTML driver in Cycle DOM can take custom modules https://github.com/cyclejs/cyclejs/issues/335
  - [x] DOM Driver supports snabbdom dataset module by default https://github.com/cyclejs/cyclejs/issues/396 
  - [x] Rx v4 no longer support
  - [x] Fixed DOM https://github.com/cyclejs/cyclejs/issues/310
  - [x] Fixed DOM https://github.com/cyclejs/cyclejs/issues/414
  - [x] Fixed DOM https://github.com/cyclejs/cyclejs/issues/222
  - [x] Drivers no longer take adapter as second arg
  - [x] Migration guide
    - [x] see matrixmultiplication.xyz example
    - [x] transposition
    - [x] how to use `@cycle/run`
  - [x] Instructions for library authors
- [x] Fix history, to do https://github.com/cyclejs/cyclejs/blob/master/history/src/makeHistoryDriver.ts#L46
- [x] Update docs, issue #520 
- [x] **Release** 🇨🇦 🇨🇦 🇨🇦 🇨🇦 🇨🇦 🇨🇦 🇨🇦 🇨🇦 🇨🇦 🇨🇦 🇨🇦 🇨🇦 
- [x] npm Deprecate `@cycle/base`
- [ ] Deprecate rx-run
- [x] npm Deprecate `@cycle/xstream-run`
- [x] npm Deprecate `@cycle/___-adapter` packages
- [x] Update docs site to `/docs`
- [x] Deprecate old site
- [x] Announce and close this issue

**Comment by whitecolor** [comment]
Simplifying is great though this will actually make cycle xstream only, which might be not so bad. But usage with other libs will be definitely ridiculously cumbersome probably thus unlikely possible anymore. 

> Except we couldn't do that for sources, 

Right, or will require again some intermediate layer ala current `diveristy`.

> Study its viability regarding migration for RxJS and most.js use cases

migrating to xstream completely

> The motivation behind this is that it would make customElementify easier (which currently only supports xstream)

Looking at the code, support for other libs could added without any problems if there would be need.

The only reason to make cycle-xstream-only-version - to get rid of need to support multiple libs, remove adapters stuff, have only single stream lib and typings in drivers, etc. Because it is really kind of cumbersome (though maybe not so ridiculous). 

So will need to deprecate all diversity stuff. Well this is kind of strategical decision maybe right for cyclejs future, maybe not so. 

Well though I want admit that I'm not against this, because I don't see big reason behind existion of multiple stream libs at all. =) **There can be only one!** Interesting what people think.

**Comment by whitecolor** [comment]
@staltz 
I dont' know what to/fromObservable API how do you assume using dirvers within non-xstream-dataflows:
```js
// probably should be something specific for lib
xs.toObservable(HTTP.select())
 .map(xs.toObservable)
```
like this?

**Comment by staltz** [comment]
It'll be easier to understand when I have something to show, and don't worry, I won't push this change over night, let's check first with the community.

**Comment by milankinen** [comment]
I'd like to add some notes from non-xs user's viewpoint:

> ... user applies xs.fromObservable/toObservable on the edges sources/sinks ... 

Does this mean that e.g. DOM event listening will be something like this?
```js
const clicks = myLib.fromObservable(DOM.select('.my .selector').events('click').toObservable())
```
IMHO, that is way too cumbersome for such a simple and common operation. 😕 

> In fact, we can even automatically apply, inside run(), xs.fromObservable(sink) if we detect that sink is not an xstream Stream.

How about if I need to create my own application specific drivers? Does that mean that I need to use `myLib.fromObservable(sink.toObsevable())` inside my driver code as well?

> The motivation behind this is that it would make customElementify easier (which currently only supports xstream)

Is this the greatest motivation behind this experiment? Web components are still a very experimental feature. Does the received benefits cover the caused troubles for RxJs/most/etc. users? I suspect that only few consider `xstream` "production ready" yet (I may be wrong, though). Have you considered how does this change affect to the existing user base or new users or cycle adoption in the industry?

I took a look at the `customElementify` codebase and I didn't find any reason why it couldn't be implemented streaming lib agnostic. Wouldn't that be easier than making a breaking change to cycle core?

**Comment by whitecolor** [comment]
I think @staltz whats to simplify things, I don't think that this proposed change is driven mostly by his ego as xstream creator :) 

I think there exists a couple of fundamental/strategical (for cyclejs) questions, that should be considered and answered.

Personally I found `xstream` very nice, it has simple and concise API, and probably can any manipulation with as streams can be accomplished using existing operators (at least within cyclejs realm). So I personally think that I wouldn't find my self in a big trouble of using only xstream in cycle projects.

So my first question sounds like: **why cycle users may want to prefere to use rx/rxj/most not xstream** when building cycle apps? I know that for example @TylorS just likes most API. Some may like Rxjs. Maybe readiness for production, and some things in `xstream` that are under considerations can be still a reason against `xstream`. I actually don't see a big reason for existing many reactive stream libs, they actually do the same thing, and even in the same manner, APIs are very a like, and rarely add more perks, but I may be wrong about it.

The second question that bothers: **why cyclejs (as project) should officially consider rx/rxjs/most? (additionally to xstream)** Why not bacon, why not kefir, whatever? Why not only `rxjs`? Is this just a "legacy" (if this term is appropriate to cycle age) support or tribute to a few active cycle users of those libs? **Isn't it a waste of time and the resources?**.

For now I think that limiting official support only to xstream would keep things more simple (for xstream users, maintainers, driver/components authors etc), but keeping diversity approach will make cycle more open (and maybe potentially more widely accepted).

It is interesting what other cycle users think about it.

**Comment by TylorS** [comment]
@whitecolor 
1. Yeah, we've come to use most.js instead of *x* at work, and I do enjoy that it has a functional API.
2. I don't know :)

I think a further consideration might be what if we were to build the next version of Cycle on **only** ES Observables? 

I think the stable parts should be the only thing we consider for usage. Mainly

```typescript
interface Observable<T> {
  from<T> (...): Observable<T>
  subscribe(observer: Observer<T>): Subscription

  [Symbol.observable]: Observable<T>
}

interface Observer<T> {
  next (value: T): void;
  error(error: any): void;
  complete(): void;
}

interface Subscription {
  unsubscribe (): void;
}
```

Cycle core can definitely be implemented using only these, and driver can convert too and from easily with `Observable.from()`

**Comment by milankinen** [comment]
> I think @staltz whats to simplify things, I don't think that this proposed change is driven mostly by his ego as xstream creator :)

You misunderstood my point 😅  My point is that these changes might simplify things for (driver) maintainers but they're definitely not simplifying things for non-xstream users. The statistical fact is that the number of RxJs users (or people familiar with RxJs) is magnitudes greater than xstream users. 

My fear is that if cycle is nailed to use `xstream`, it drops the amount of potential users to only a fraction of it's now with diversity support, and in the end only hipsters are using cycle (until they found new stuff). IMHO the diversity support is crucial for growth and mainstream adoption.

> I think a further consideration might be what if we were to build the next version of Cycle on only ES Observables?

That sounds definitely something worth of experimenting! 👍

**Comment by staltz** [comment]
We are likely going to do this #425 together with #432 **as an experiment** and we have ideas that would make it unnecessary to do 

```js
myLib.fromObservable(DOM.select('.my .selector').events('click').toObservable())
```

But it's an experiment, and as I said:

> don't worry, I won't push this change over night, let's check first with the community.

**Comment by whitecolor** [comment]
@milankinen 
> You misunderstood my point

Think it is not "only your" point :smile: 

> it drops the amount of potential users to only a fraction of it's now with diversity support, and in the end only hipsters are using cycle (until they found new stuff). IMHO the diversity support is crucial for growth and mainstream adoption.

I wonder if this is true. I'm inclined to think that it is sensible consideration.

>  we have ideas that would make it unnecessary to do

Interesting to see. I see the only not so cumbersome option:

```js
DOM.select('.my .selector').events('click').as(rxStream /* some converter*/)
```

**Comment by donaldpipowitch** [comment]
> why cycle users may want to prefere to use rx/rxj/most not xstream when building cycle apps?

AFAIK RxJS is developed as a polyfill for ES Observables. That's why I default to RxJS in general.

**Comment by staltz** [comment]
The way ES Observable is going, ES Observable will be different to RxJS. You won't be able to drop RxJS and just use native Observables. Unfortunately.

**Comment by donaldpipowitch** [comment]
Sad to hear that! :(

**Comment by SteveALee** [comment]
I was only thinking a few days ago that one of the advantages of original CycleJS was it was tiny and easy to read. Will this get back to that?

I'd be happy if it was xstream out of the box but other stream libs are possible for those not wanting to learn another or with existing code.

Shame about ES Observable :(

**Comment by staltz** [comment]
Yes this would drastically simplify the Cycle.js codebase, basically eliminating `@cycle/base` and `@cycle/____-adapter`

**Comment by mightyiam** [comment]
Did I miss anything about ES Observable?

**Comment by whitecolor** [comment]
> Yes this would drastically simplify the Cycle.js codebase

No so drastically instead of adapters, it will just removes adapters. Still not sure maybe it is a better approach than with adapters (esp. in case [observables will be come so fantastically compatible](https://github.com/staltz/fantasy-observable)). Also hope xstream's internal stuff like async stream completion  (based on setTimeout) won't introduce issues for some edge cases.

**Comment by staltz** [comment]
TC39 Observable is crap, we're going to follow https://github.com/staltz/fantasy-observable. The spec process should be led by proven, battle-tested technology, not the other way around. Brian Cavalier and Paul Taylor agree.

**Comment by staltz** [comment]
> Also hope xstream's internal stuff like async stream completion (based on setTimeout) won't introduce issues for some edge cases.

It shouldn't, all drivers were already written with xstream.

**Comment by SteveALee** [comment]
https://en.wikipedia.org/wiki/Second-system_effect 
Just sayin :)

**Comment by lmatteis** [comment]
Are there any examples on how the toObservable/fromObservable pattern will work for driver authors? Actually it would be nice to get an example from both the user perspective as well as the author perspective. As I understand, driver authors won't need to use runStreamAdapter anymore, but it's still unclear.

**Comment by whitecolor** [comment]
@staltz btw you may want to use "extends" feature of tsconfig https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#configuration-inheritance to simplify tsconfig management.

scripts in `package.json`s could be unified also, it is really not dry to have all the same in each package.

**Comment by artfuldev** [comment]
I want to help, but is this build-able on Windows?

**Comment by staltz** [comment]
Hi @artfuldev, check out this issue: https://github.com/cyclejs/cyclejs/issues/384

**Comment by artfuldev** [comment]
thanks! do have windows with the ubuntu bash, good to know.

**Comment by ntilwalli** [comment]
@staltz Would you consider upgrading superagent to v3.* for the HTTP driver in the 'unified' branch?  Superagent 3.* is Rollup compatible.  The 2.* versions are not Rollup compatible due to the issue fixed here: https://github.com/visionmedia/superagent/pull/1088

**Comment by staltz** [comment]
Great point, thanks @ntilwalli.

**Comment by Widdershin** [comment]
I rewrote the JSONP driver, #513. Needs review 😄

**Comment by staltz** [comment]
Bringing something to the attention of others, I wrote some piece of code that looks pretty ugly but proves critical to solve a corner case. Check this out:
https://github.com/cyclejs/cyclejs/commit/58b7991a19b47ff8589ead7df1f5131605a28916#diff-5fc600a68bfbc0ac7d28466ec8fab505R145
(read the commit message and the comments)

```js
const complete = () => { 
  setTimeout(() => { listener._c(); }, EARLIEST_SINK_COMPLETE); 
};
```

I need some feedback what to do, because it **seems** like we could remove sink proxy completion (`listener._c()`) entirely. Basically, this would make all sinks never complete, from the perspective of drivers. This **might** be okay since drivers are supposed to exist through the whole execution of the program, and are not meant to be reused. A single driver will only receive one sink, ever. For disposal, we have two approaches:
- Source disposal (e.g. in the DOM driver, the DOM source's `.dispose()` will be called when Cycle run's execution is disposed, which will trigger `sanitation$`, which will `endWhen` the sink)
- Sink proxy replication disposal (detaches the sink proxy from the sink)

These two seem sufficient to cover disposal of sinks.

So, asking @whitecolor @TylorS @Widdershin, do you see any need to have drivers receive `complete` from sink (proxies)? Removing the complete would allow us to get rid of this ugly setTimeout.

**Comment by whitecolor** [comment]
@staltz 
So the problem is that sink stream may be completed before it is subscribed. This case, of course, should not be handled using `setTimeout` inside cycle, especially using some empiric timeout value,  such things should be strictly avoided. I think never completing sink is ok, I can not imagine driver that would expect sink stream that ends.

**Comment by geovanisouza92** [comment]
@whitecolor @staltz Maybe a driver expect a completion to do some kind of cleanup? (WebSocket, opened files...)

**Comment by whitecolor** [comment]
@geovanisouza92 it can be done in source's dispose function

@staltz but I think that all `sinkProxies` should be disposed/completed when cycle's `dispose` is called (now it is not done), then it would be possible for driver could handle sink completion as well.

**Comment by staltz** [comment]
> but I think that all sinkProxies should be disposed/completed when cycle's dispose is called

Good point! I'll do these changes in the unified branch and see if all tests and important examples run correcly.

**Comment by staltz** [comment]
@geovanisouza92 
> Maybe a driver expect a completion to do some kind of cleanup? (WebSocket, opened files...)

Yes, completion should happen, and we still will have completion. The difference is:
1. If the real sink completes early, the driver will receive completion only when the Cycle app is disposed.
2. If the real sink never completes, the driver will anyway receive completion when the Cycle app is disposed.

(1) means that cleanup will happen later than usual. This is only a problem if a driver creates a ton of resources upfront, which should be disposed as soon as possible. I don't think that's realistic, probably not the case for any of the drivers so far.

(2) is a really good thing. Even if the real sink never completes (imagine the programmer forgot to make sure every sink completes), the driver will still receive completion. It becomes a guarantee.

This is already now done and committed to the unified branch.

**Comment by SteveALee** [comment]
Fantastic to see this closed! Awesome work
